## kubectl apply -f kubernetes/prometheus/prometheus_config.yaml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'hello-world-api'
    static_configs:
      - targets: ['localhost:3000']  #ip du pod à decouvrir?