# recupere le build , lance un cluster k8S et deploy l'image
  name: cd_workflow

  on:
    workflow_dispatch: # TODO remplacer par push tag 
  # push:
  #   tags:
  #     - '*'
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build -t your-dockerhub-username/your-image-name:latest . --push

    deploy_release:
      runs-on: mon_serveur
      steps:
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy API to Kubernetes
        run: |
         kubectl apply -f kubernetes/api-hello-world/api_deployment.yml 

      - name: Expose service to Kubernetes
        run: |
         kubectl apply -f kubernetes/api-hello-world/api_service.yml 

