# recupere le build , lance un cluster k8S et deploy l'image
  name: cd_workflow

  on:
  # push:
  #   tags:
  #     - '*'
   workflow_dispatch: # TODO commenter apres debbuggage

  jobs:
    deploy_release:
      runs-on: mon_serveur    
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
  
          # met en place un jeu de cle ssh
        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.5.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
        - name: Execute Commands Locally
          uses: appleboy/ssh-action@master
          with:
            host: ${{ matrix.host }}
            username: ${{ env.QBP_SERVER_USERNAME }}
            password: ${{ env.QBP_SERVER_PASSWORD }}
            port: 22
            script:   "cd ${{ENV.PATH_PROJET}} && \
                                   echo lancement du script && \
                                   pwd && \
                                   docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} && \
                                   docker pull api-avproject:latest && \
                                   docker tag api-avproject:latest api && \
                                   kubectl apply -f kubernetes/api-hello-world/api_deployment.yml  && \
                                   kubectl apply -f kubernetes/api-hello-world/api_service.yml "
                                  


